services:
  - type: web
    name: helpdesk-ticketing
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn helpdesk_ticketing.wsgi:application"
    envVars:
      - key: PRODUCTION
        value: "True"
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: "5432"
      - key: SCHEMA
        value: "public"
      - key: SUPABASE_S3_ACCESS_KEY_ID
        sync: false
      - key: SUPABASE_S3_SECRET_ACCESS_KEY
        sync: false
      - key: SUPABASE_S3_BUCKET
        value: "attachments"
      - key: SUPABASE_S3_ENDPOINT_URL
        sync: false
      - key: SUPABASE_S3_REGION
        sync: false
      - key: EMAIL_HOST
        value: "smtp.zoho.com"
      - key: EMAIL_PORT
        value: "465"
      - key: EMAIL_USE_SSL
        value: "True"
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: DEFAULT_FROM_EMAIL
        sync: false
      - key: IMAP_HOST
        value: "imap.gmail.com"
      - key: IMAP_PORT
        value: "993"
      - key: IMAP_USE_SSL
        value: "True"
      - key: IMAP_USERNAME
        sync: false
      - key: IMAP_PASSWORD
        sync: false

  - type: cron
    name: fetch-emails
    runtime: python
    plan: free
    schedule: "*/10 * * * *"
    buildCommand: "./build.sh"
    startCommand: "python manage.py fetch_emails"
    envVars:
      - key: PRODUCTION
        value: "True"
      - fromService:
          type: web
          name: helpdesk-ticketing
          envVarKey: SECRET_KEY
        key: SECRET_KEY
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: "5432"
      - key: SCHEMA
        value: "public"
      - key: SUPABASE_S3_ACCESS_KEY_ID
        sync: false
      - key: SUPABASE_S3_SECRET_ACCESS_KEY
        sync: false
      - key: SUPABASE_S3_BUCKET
        value: "attachments"
      - key: SUPABASE_S3_ENDPOINT_URL
        sync: false
      - key: SUPABASE_S3_REGION
        sync: false
      - key: IMAP_HOST
        value: "imap.gmail.com"
      - key: IMAP_PORT
        value: "993"
      - key: IMAP_USE_SSL
        value: "True"
      - key: IMAP_USERNAME
        sync: false
      - key: IMAP_PASSWORD
        sync: false
