# Generated by Django 6.0.7 on 2026-07-10 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_code',
            field=models.CharField(blank=True, db_index=True, max_length=20, unique=True),
        ),
    ]
